### ISSUE TITLE
翻译HtDP Languages和Teachpacks文档

### ISSUE THREAD

**Issue by mrmathematica** [Racket-zh/racket#7]
HtDP2e中文版权已被人民邮电出版社购买，预计2018年底或2019年初出版。和2003年的HtDP配套英文DrScheme界面不同，新版会采用DrRacket简体中文界面。如果能配套提供对应Languages和Teachpacks文档，应该能对推广本书和Racket在中文世界起到积极作用。

https://docs.racket-lang.org/htdp-langs/index.html
https://docs.racket-lang.org/teachpack/index.html

**Comment by OlingCat** [comment]
此项目翻译见 https://github.com/Racket-zh/htdp

**Comment by mrmathematica** [comment]
初译完成。

**Comment by OlingCat** [comment]
咱也得加速填坑进度了= =
